### ISSUE TITLE
[bug?] Icon very broken

### ISSUE THREAD

**Issue by ItsDrCat** [SomnathChW/BetterRTX-Installer-GUI#6]
The icon for BetterRTX.exe appears to not be scaled correctly and becomes this very squished BRTX On logo.
![Screenshot 2023-07-25 124005](https://github.com/SomnathChW/BetterRTX-Installer-GUI/assets/114036615/a196e99a-0ba1-434f-8916-883be456d060)

**Comment by ItsDrCat** [comment]
note: I did make a crude and quick icon that fixes this problem.

**Comment by ItsDrCat** [comment]
note1: accidentally closed issue
note2: I did create a crude icon that does fix this issue and could be used as a placeholder icon if you want to
![logo](https://github.com/SomnathChW/BetterRTX-Installer-GUI/assets/114036615/23526465-aed2-4419-afe3-5f411d98f3f7)
(has to be converted back to .ico)

**Comment by SomnathChW** [comment]
Added in v0.0.3
